name: Deploy Frontend to Azure
on:
  push:
    branches: [ main, lolo ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Poetry
      run: |
        pip install --user pipx
        pipx install poetry==1.5.1
    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-root
    - name: Export requirements
      run: poetry export -f requirements.txt --output requirements.txt --without-hashes
    - name: Display error log
      if: failure()
      run: cat /home/runner/work/DataScienceProject-front/DataScienceProject-front/poetry-installer-error-*.log
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'datascienceproject-frontend-12345'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}